import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

//terms section
const sections = [
    {
        title: '1. Acceptance of Terms',
        body: 'By creating an account or using Brainy ("the Service"), you agree to be bound by these Terms & Conditions. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these terms.',
    },
    {
        title: '2. Description of Service',
        body: 'Brainy provides automated static and AI-assisted analysis of source code submitted by users, including bug detection, complexity scoring, quality scoring, and AI-generated code suggestions. The Service is provided on an "as-is" and "as-available" basis.',
    },
    {
        title: '3. Your Content',
        body: 'You retain all ownership rights to source code and files you upload or paste into the Service ("Your Content"). By submitting Your Content, you grant Brainy a limited, non-exclusive license to process, store, and analyze Your Content solely for the purpose of providing the Service to you, including transmitting Your Content to third-party AI inference providers as described in our Privacy Policy.',
    },
    {
        title: '4. Acceptable Use',
        body: 'You agree not to upload code that you do not have the legal right to submit, code containing malware or intentionally malicious payloads for unauthorized deployment, or any content that infringes the intellectual property rights of a third party. Brainy reserves the right to suspend accounts found in violation of this policy.',
    },
    {
        title: '5. AI-Generated Suggestions',
        body: 'Suggested fixes, rewrites, and severity scores are generated by third-party large language models and automated heuristics. They are provided for informational purposes only and do not constitute a guarantee of correctness, security, or fitness for production use. You are solely responsible for reviewing and testing any suggested code before deployment.',
    },
    {
        title: '6. Account Responsibility',
        body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify us immediately of any unauthorized use of your account.',
    },
    {
        title: '7. Termination',
        body: 'We may suspend or terminate your access to the Service at our discretion if we believe these Terms have been violated. You may delete your account at any time; deletion will remove your projects and files from our systems subject to standard backup retention windows.',
    },
    {
        title: '8. Limitation of Liability',
        body: 'To the maximum extent permitted by law, Brainy and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to reliance on AI-generated code suggestions.',
    },
    {
        title: '9. Changes to These Terms',
        body: 'We may update these Terms from time to time. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.',
    },
    {
        title: '10. Contact',
        body: 'Questions about these Terms can be directed to the project maintainers via the GitHub repository linked in the footer.',
    },
];

export default function Terms() {
    return (
        <div className="relative min-h-screen bg-bg text-text px-6 py-16">
            <div className="ambient-glow" />
            <div className="relative z-10 max-w-3xl mx-auto">
                <Link to="/" className="flex items-center gap-2 text-sm text-text-muted hover:text-text transition mb-10">
                    <ArrowLeft size={15} /> Back home
                </Link>

                <div className="glass-card rounded-2xl p-8 md:p-10">
                    <h1 className="font-display text-3xl font-bold mb-2">Terms & Conditions</h1>
                    <p className="text-xs text-text-muted uppercase tracking-widest mb-8">
                        Last updated: {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
                    </p>

                    <div className="space-y-6">
                        {sections.map((s) => (
                            <div key={s.title}>
                                <h2 className="font-semibold text-text mb-1.5">{s.title}</h2>
                                <p className="text-sm text-text-muted leading-relaxed">{s.body}</p>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>
    );
}